alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias eth0='enp0s25'
alias postweb='/gitclones/postWebTerminal/postweb.sh'
alias passgen='/gitclones/shellPasswd/passgen.sh'
alias ll='ls -lah --color=auto'
alias i3conf='vim ${HOME}/.config/i3/config'

