alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias eth0='enp0s25'
alias yourl='/gitclones/yoURL/yourl.sh'
alias passgen='/gitclones/shellPass/shellpass.sh'
alias shellPass='/gitclones/shellPass/shellPass.sh'
alias ll='ls -lah --color=auto'
alias i3conf='vim ${HOME}/.config/i3/config'
alias morpheus='ssh -p 10024 modengo@192.168.2.185'
alias orico01s='sshfs -p 10024 modengo@192.168.2.185:/mnt/Orico01S /mnt/Orico01S/'
alias orico02t='sshfs -p 10024 django@192.168.2.185:/mnt/Orico02T /mnt/Orico02T/'
